[workspace]
members = ["polars-app", "polars-rw", "polars-use", "utils"]
resolver = "2"
default-members = ["polars-app"]

[workspace.dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
chrono = "0.4.42"
polars = { version = "0.52.0", features = [
  "concat_str",
  "dtype-categorical",
  "lazy",
  "strings",
  "json",
  "regex",
  "timezones",
] }
